# OpenAPI fragment placeholder - to be completed verbatim from Snowflake docs
openapi: 3.0.3
info:
  title: Snowpipe Streaming - Exchange Scoped Token
  version: 0.1.0
paths:
  /oauth/token:
    post:
      summary: Exchange JWT for Snowpipe Streaming scoped token
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                grant_type:
                  type: string
                  enum: ["urn:ietf:params:oauth:grant-type:jwt-bearer"]
                scope:
                  type: string
                  description: The hostname of the account
              required: [grant_type, scope]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                required: [token]
