# OpenAPI fragment placeholder - to be completed verbatim from Snowflake docs
openapi: 3.0.3
info:
  title: Snowpipe Streaming - Open Channel
  version: 0.1.0
paths:
  /v2/streaming/databases/{databaseName}/schemas/{schemaName}/pipes/{pipeName}/channels/{channelName}:
    put:
      summary: Create or open a streaming channel
      parameters:
        - in: path
          name: databaseName
          required: true
          schema: { type: string }
        - in: path
          name: schemaName
          required: true
          schema: { type: string }
        - in: path
          name: pipeName
          required: true
          schema: { type: string }
        - in: path
          name: channelName
          required: true
          schema: { type: string }
        - in: query
          name: requestId
          required: false
          schema: { type: string, format: uuid }
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                offset_token:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  next_continuation_token: { type: string }
                  channel_status:
                    type: object
                    properties:
                      database_name: { type: string }
                      schema_name: { type: string }
                      pipe_name: { type: string }
                      channel_name: { type: string }
                      channel_status_code: { type: string }
                      last_committed_offset_token: { type: string }
                      created_on_ms: { type: integer, format: int64 }
                      rows_inserted: { type: integer }
                      rows_parsed: { type: integer }
                      rows_error_count: { type: integer }
                      last_error_offset_upper_bound: { type: string }
                      last_error_message: { type: string }
                      last_error_timestamp: { type: integer, format: int64 }
                      snowflake_avg_processing_latency_ms: { type: integer }
                required: [next_continuation_token]
